Repository DXHeroes/dx-scanner, pull requests merged in 2019-10, with the labels that each got.

#74 fix(GitService): change join for resolve
  src/services/git/Git.ts
Labels: Difficulty: Easy, Priority: High, Status: In Progress, Type: Bug

#77 feat(cli): add update-notifier
  package.json
  src/index.ts
  yarn.lock
Labels: Hacktoberfest, Status: Review Needed, Type: Enhancement

#84 Language Detector for Python
  src/contexts/scanner/scannerContextBinding.ts
  src/detectors/Python/PythonLanguageDetector.spec.ts
  src/detectors/Python/PythonLanguageDetector.ts
  src/model.ts
Labels: Hacktoberfest, Hacktoberfest: Approved, Type: Enhancement

#85 docs: add links to DXKB articles
  src/practices/JavaScript/JsBackendTestingFrameworkUsedPractice.ts
  src/practices/LanguageIndependent/CIUsedPractice.ts
  src/practices/LanguageIndependent/DockerizationUsedPractice.ts
  src/practices/LanguageIndependent/ReadmeIsPresentPractice.ts
  src/practices/PackageManagement/LockfileIsPresentPractice.ts
Labels: Priority: High, Type: Documentation

#57 docs: add demo image
  README.md
  demo.svg
  src/reporters/CLIReporter.ts
Labels: Type: Documentation

#86 feature/bitbucket integration
  .eslintrc.json
  package.json
  src/contexts/scanner/scannerContextBinding.ts
  src/detectors/ScanningStrategyDetector.spec.ts
  src/detectors/ScanningStrategyDetector.ts
  src/detectors/utils/ScanningStrategyDetectorUtils.ts
  src/index.ts
  src/inspectors/CollaborationInspector.spec.ts
  src/inspectors/IssueTrackingInspector.spec.ts
  src/inspectors/IssueTrackingInspector.ts
  src/inversify.config.ts
  src/lib/deepRequired.ts
  src/scanner/Scanner.ts
  src/services/bitbucket/BitbucketService.spec.ts
  src/services/bitbucket/BitbucketService.ts
  src/services/git/Git.spec.ts
  src/services/git/Git.ts
  src/services/git/GitHubService.spec.ts
  src/services/git/GitHubService.ts
  src/services/git/ICVSService.ts
  src/services/git/IGitHubService.ts
  src/services/git/__MOCKS__/bitbucketServiceMockFolder/getIssueCommentsResponse.ts
  src/services/git/__MOCKS__/bitbucketServiceMockFolder/getIssueResponse.ts
  src/services/git/__MOCKS__/bitbucketServiceMockFolder/getIssuesResponse.ts
  src/services/git/__MOCKS__/bitbucketServiceMockFolder/getPullCommits.ts
  src/services/git/__MOCKS__/bitbucketServiceMockFolder/getPullRequestResponse.ts
  src/services/git/__MOCKS__/bitbucketServiceMockFolder/getPullRequestsResponse.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getContributorsServiceResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getContributorsStatsResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getContributorsStatsServiceResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getIssueCommentsResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getIssueCommentsServiceResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getIssueResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getIssueServiceResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getIssuesResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getIssuesServiceResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getPullRequestsReviewsResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getPullServiceResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getPullsCommitsResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getPullsReviewsServiceResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getPullsServiceResponse.mock.ts
  src/services/git/__MOCKS__/gitHubServiceMockFolder/getRepoCommitsResponse.mock.ts
  src/services/git/model.ts
  test/helpers/bitbucketNock.ts
  test/helpers/gitHubNock.ts
  yarn.lock
Labels: Priority: High, Type: Enhancement

#94 docs: switch license to MIT
  LICENSE
  README.md
  package.json
Labels: Type: Documentation

#97 Compute DX Score of each Component and overall DX Score
  .gitignore
  .travis.yml
  codecov.yml
  package.json
  src/detectors/JavaScript/JavaScriptComponentDetector.ts
  src/lib/deepPartial.ts
  src/practices/Collaboration/PullRequestPractice.ts
  src/practices/JavaScript/DeprecatedTSLintPractice.spec.ts
  src/practices/JavaScript/DeprecatedTSLintPractice.ts
  src/practices/JavaScript/JsGitignoreCorrectlySetPractice.ts
  src/practices/Testing/UnitTestPractice.ts
  src/practices/index.ts
  src/reporters/CLIReporter.ts
  src/reporters/ReporterUtils.spec.ts
  src/reporters/ReporterUtils.ts
  src/reporters/model.ts
  src/scanner/Scanner.ts
  test/factories/PracticeWithContextFactory.ts
Labels: Type: Enhancement

#126 doc: Add Flags Usage and Score Counting section into Readme
  README.md
  src/index.ts
Labels: Type: Documentation
