Repository DXHeroes/dx-scanner, pull requests merged in 2019-08, with the labels that each got.

#1 Add Travis CI
  .travis.yml
  package.json
Labels: enhancement

#2 feat(cli): change default command to "dxscanner"
  README.md
  package.json
Labels: documentation, enhancement

#3 feat(README): add more badges in the README
  .travis.yml
  README.md
  codecov.yml
  package.json
  yarn.lock
Labels: documentation, enhancement

#9 docs: add all contributors behind code
  .all-contributorsrc
  README.md
Labels: documentation

#19 Chore: fix running practices
  package.json
  src/detectors/utils.spec.ts
  src/practices/JavaScript/TypeScriptUsedPractice.spec.ts
  src/reporters/CLIReporter.ts
  src/scanner/Scanner.ts
  yarn.lock
Labels: bug

#20 ci(multiOS): add windows, osx and linux as matrix for Travis CI
  .travis.yml
  package.json
  src/detectors/JavaScript/JavaScriptLanguageDetector.spec.ts
  src/detectors/JavaScript/JavaScriptLanguageDetector.ts
  src/detectors/javascript.ts
  src/detectors/utils.spec.ts
  src/detectors/utils.ts
  src/inspectors/CollaborationInspector.spec.ts
  src/inspectors/FileInspector.ts
  src/inspectors/ICollaborationInspector.ts
  src/inspectors/IFileInspector.ts
  src/inspectors/package/JavaScriptPackageInspector.spec.ts
  src/inversify.config.ts
  src/practices/JavaScript/JsGitignoreCorrectlySetPractice.spec.ts
  src/practices/JavaScript/JsGitignoreIsPresentPractice.spec.ts
  src/practices/JavaScript/JsPackageJsonConfigurationSetCorrectlyPractice.spec.ts
  src/practices/JavaScript/JsPackageManagementUsedPractice.spec.ts
  src/practices/LanguageIndependent/CIUsedPractice.spec.ts
  src/practices/LanguageIndependent/DependenciesVersionPractice.spec.ts
  src/practices/LanguageIndependent/DockerizationUsedPractice.spec.ts
  src/practices/LanguageIndependent/EditorConfigIsPresentPractice.spec.ts
  src/practices/LanguageIndependent/LicenseIsPresentPractice.spec.ts
  src/practices/LanguageIndependent/ReadmeIsPresentPractice.spec.ts
  src/practices/PackageManagement/LockfileIsPresentPractice.spec.ts
  src/services/FileSystemService.real.spec.ts
  src/services/FileSystemService.spec.ts
  src/services/FileSystemService.ts
  src/services/FileSystemService.virtual.spec.ts
  src/services/IFileSystemService.ts
  src/services/IVirtualFileSystemService.ts
  src/services/VirtualFileSystemService.spec.ts
  src/services/VirtualFileSystemService.ts
  src/services/__MOCKS__/mockFolder/mockFile.ts
  src/services/__MOCKS__/mockFolder/mockFileSL.ts
  src/services/__MOCKS__/mockFolderSL
  src/services/model.ts
  yarn.lock
Labels: bug

#28 chore: add semantic release automation
  .travis.yml
  CHANGELOG
  CHANGELOG.md
  package.json
  yarn.lock
Labels: documentation

#36 Fixed paths to index.js for the real runtime
  .gitignore
  bin/run
  package.json
  src/contexts/projectComponent/ProjectComponentContext.ts
  src/scanner/Scanner.ts
  src/services/git/Git.ts
  src/services/git/GitHubUrlParser.ts
Labels: bug
